name: CI
on: 
    push:
    workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: initialization
      run: |
        git config --global user.name ${{ secrets.GitHubName }}
        git config --global user.email ${{ secrets.GitHubMail }}
        git config --global credential.helper store
        echo "https://Wi-nnie:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
    - name: Setup upterm session
      run: |
        git clone https://github.com/tmux/tmux.git
        cd tmux
        sh autogen.sh
        ./configure && make
        tmux -d
      timeout-minutes: 300
