name: CI
on: 
    push:
    workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: initialization
      run: |
        git config --global user.name ${{ secrets.GitHubName }}
        git config --global user.email ${{ secrets.GitHubMail }}
        git config --global credential.helper store
        echo "https://Wi-nnie:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
    - name: Start SSH via tmate
      uses: rdp-studio/ssh2actions@main
      timeout-minutes: 300
